---
- name: tljh setup
  hosts: tljh_server
  become: true
  gather_facts: true

  roles:
    - role: base
      tags: base

    - role: postgresql
      tags: postgresql

    - role: jupyterhub
      tags: jupyterhub

    - role: exam_lockdown
      tags: exam_lockdown

    - role: exam_trash
      tags: exam_trash

    - role: firewall
      tags: firewall

    - role: skel
      tags: skel

    - role: helper_scripts
      tags: helper_scripts
