---
- name: Reload tljh config
  ansible.builtin.command:
    cmd: /opt/tljh/hub/bin/tljh-config reload
  changed_when: true

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Regenerate traefik config
  ansible.builtin.command:
    cmd: >-
      /opt/tljh/hub/bin/python3 -c
      "from tljh import traefik; traefik.ensure_traefik_config('/opt/tljh/state')"
  changed_when: true
  notify: Restart traefik

- name: Restart traefik
  ansible.builtin.systemd:
    name: traefik
    state: restarted

- name: Restart examauth-monitor
  ansible.builtin.systemd:
    name: examauth-monitor
    state: restarted
